language: cpp
os: linux
sudo: required
dist: focal

branches:
  only:
  - master

addons:
  apt:
    update: true
    packages:
      - cmake-data
      - cmake-extras
      - cmake
      - clang
      - llvm
      - libedit-dev
      - doxygen
      - graphviz
      - libfmt-dev
      - libboost-all-dev
      - libgtest-dev
      - libprotobuf-dev
      - protobuf-compiler

before_install:
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 13

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j `nproc`
  - make test

after_success:
    - echo "Build Success"
