language: cpp

dist: focal

branches:
  only:
  - master

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libboost-dev-all
      - libgtest-dev
      - libprotobuf-dev
      - protobuf-compiler

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j `nproc`
  - make test

after_success:
    - echo "Build Success"
